# tessera_shapes.pyi

from typing import Any, Tuple, TypeVar, Generic

T = TypeVar("T")

class Dim:
    def __init__(self, name: str): ...

class Tensor(Generic[T]):
    shape: Tuple[Any, ...]
    dtype: Any
    def __init__(self, shape: Tuple[Any, ...], dtype: Any): ...
    def __matmul__(self, other: "Tensor") -> "Tensor": ...
    def transpose(self, axes: Tuple[int, ...]) -> "Tensor": ...

def sym(names: str) -> Tuple[Dim, ...]: ...
def check_shapes(fn): ...
